fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.1.0
    concat:
      repo: git://github.com/puppetlabs/puppetlabs-concat.git
      ref: 1.1.0
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: 1.0.2
    mysql:
      repo: git://github.com/puppetlabs/puppetlabs-mysql.git
      ref: 2.2.3
    augeasproviders:
      repo: git://github.com/hercules-team/augeasproviders.git
      ref: v1.0.2
    logrotate:
      repo: git://github.com/rodjek/puppet-logrotate.git
      ref: 1.1.1
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
      ref: 0.0.6
    limits:
      repo: git://github.com/saz/puppet-limits.git
      ref: v2.0.1
  symlinks:
    slurm: "#{source_dir}"
    site_slurm: "#{File.join(source_dir, 'tests', 'site_slurm')}"